# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aB43ZsKnKc1XVt-JBfxMGysr5BTHu8p7
"""

import pandas as pd
import tensorflow as tf

data = pd.read_csv("train.csv")
data.head()

data.info()

data.isnull().sum()

data["Age"] = data["Age"].fillna(data["Age"].median())

data["Sex"] = data["Sex"].map({"male": 0,"female": 1})

data["Embarked"] = data["Embarked"].fillna(data["Embarked"].mode()[0])

data = pd.get_dummies(data,columns=["Embarked"],dtype=int)

data.isnull().sum()

features = [
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked_C",
    "Embarked_Q",
    "Embarked_S"
]

target = ["Survived"]

X = data[features]
y = data[target]

print("X shape:", X.shape)
print("y shape:", y.shape)

dataset = tf.data.Dataset.from_tensor_slices((X.values, y.values))

train_data, test_data = tf.keras.utils.split_dataset(dataset,left_size=0.8,shuffle=True)

train_data = train_data.batch(32)
test_data = test_data.batch(32)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation="relu"),
    tf.keras.layers.Dense(8, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    train_data,
    epochs=20,
    validation_data=test_data
)

model.save("titanic_model.keras")

test_loss, test_accuracy = model.evaluate(test_data)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

